---
sudo:     false
language: ruby
cache:    bundler
before_install:
  - gem update --system
script:
  - bundle exec rake
rvm:
  - 2.3
  - 2.6
  - ruby-head
  - jruby-9.1.0.0
  - jruby-9.2.0.0
  - jruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
